name: "digita-plugins-free"
repoURL: "https://github.com/digitaplatform/digita-plugins-free.git"
owner: "digitaplatform"
onboardedAt: "2026-10-09T12:56:54.275Z"
suspended: false
quiesced: false
removing: false
builds: []
