name: "digita-plugins-store"
repoURL: "https://github.com/digitaplatform/digita-plugins-store.git"
owner: "digitaplatform"
onboardedAt: "2026-10-09T12:59:24.810Z"
suspended: false
quiesced: false
removing: false
builds: []
