name: "digita-auth"
repoURL: "https://github.com/digitaplatform/digita-auth.git"
owner: "simetrix"
onboardedAt: "2026-09-28T11:30:09.827Z"
suspended: false
quiesced: false
removing: false
builds: ["digita-auth-backend","digita-auth-frontend"]
