name: "digita-auth"
repoURL: "https://github.com/digitaplatform/digita-auth.git"
repoCredentialId: "cred_01M2GP5CPXSD5THKAXQP4BDM8F"
owner: "simetrix"
onboardedAt: "2026-09-14T19:27:56.821Z"
suspended: false
quiesced: false
removing: false
builds: ["digita-auth-backend","digita-auth-frontend"]
