name: "digita-auth"
repoURL: "https://github.com/digitaplatform/digita-auth.git"
repoCredentialId: "cred_01M298MGXP78VZFYC1CV0E16WM"
owner: "simetrix"
onboardedAt: "2026-09-11T22:17:24.395Z"
suspended: false
quiesced: false
chartPath: "deploy/chart"
cluster: "apps4"
databases: ["digita_auth"]
keyPatterns: ["digita:auth:*"]
services: ["mongodb","registry-pull","redis"]
size: "small"
mongodb: "shared"
quota: {"requestsCpu":"400m","requestsMemory":"1Gi","limitsCpu":"1500m","limitsMemory":"2Gi","pods":8,"persistentVolumeClaims":1}
