name: "hostyour-demo-consumer"
repoURL: "https://github.com/simetrixch/hostyour-demo-consumer.git"
owner: "demo"
onboardedAt: "2026-10-07T02:53:24.906Z"
suspended: false
quiesced: false
removing: false
builds: ["hostyour-demo-consumer"]
