name: "hostyour-demo-consumer"
repoURL: "https://github.com/simetrixch/hostyour-demo-consumer.git"
owner: "demo"
onboardedAt: "2026-10-07T13:12:13.972Z"
suspended: false
quiesced: false
removing: false
builds: ["hostyour-demo-consumer"]
