name: "digita-post"
repoURL: "https://github.com/digitaplatform/digita-post.git"
repoCredentialId: "cred_01M2GCQGPC9E27MPY2DAXGE1PJ"
owner: "simetirx"
onboardedAt: "2026-09-14T16:43:25.197Z"
suspended: false
quiesced: false
removing: false
builds: ["digita-post"]
