name: "digita-post"
repoURL: "https://github.com/digitaplatform/digita-post.git"
repoCredentialId: "cred_01M2VKVDRX5HD4RV8X7SRDWDHQ"
owner: "simetrix"
onboardedAt: "2026-09-19T01:19:42.809Z"
suspended: false
quiesced: false
removing: false
chartPath: "deploy/chart"
cluster: "apps7"
databases: ["digita_post"]
keyPatterns: []
channelPatterns: []
services: ["mongodb","registry-pull","postfix","smtp-ops"]
size: "small"
mongodb: "shared"
quota: {"requestsCpu":"400m","requestsMemory":"1Gi","limitsCpu":"1500m","limitsMemory":"2Gi","pods":8,"persistentVolumeClaims":1}
host: "post"
