name: "digita-post"
repoURL: "https://github.com/digitaplatform/digita-post.git"
repoCredentialId: "cred_01M2RN1PNMA2D5NX9T9VYE7H15"
owner: "simetrix"
onboardedAt: "2026-09-18T21:08:40.566Z"
suspended: false
quiesced: false
removing: false
chartPath: "deploy/chart"
cluster: "apps8"
databases: ["digita_post"]
keyPatterns: []
channelPatterns: []
services: ["mongodb","registry-pull","postfix","smtp-ops"]
size: "small"
mongodb: "shared"
quota: {"requestsCpu":"400m","requestsMemory":"1Gi","limitsCpu":"1500m","limitsMemory":"2Gi","pods":8,"persistentVolumeClaims":1}
host: "post"
