{{- $env := required "global.env is required" .Values.global.env -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.digitaTests.reporter.esoServiceAccountName }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: tekton-reporter-vault
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ required "global.endpoints.vault.url is required" .Values.global.endpoints.vault.url | quote }}
      path: {{ required "global.vaultKvMount is required" .Values.global.vaultKvMount | quote }}
      version: v2
      auth:
        kubernetes:
          mountPath: {{ required "global.vaultKubernetesAuthPath is required" .Values.global.vaultKubernetesAuthPath | quote }}
          role: {{ .Values.digitaTests.reporter.vaultRole }}
          serviceAccountRef:
            name: {{ .Values.digitaTests.reporter.esoServiceAccountName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digita-tekton-reporter
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: OnChange
  refreshInterval: "0"
  secretStoreRef:
    name: tekton-reporter-vault
    kind: SecretStore
  target:
    name: digita-tekton-reporter
    creationPolicy: Owner
  data:
{{- range $property := list "app-id" "installation-id" "private-key" }}
    - secretKey: {{ $property }}
      remoteRef:
        key: {{ printf "%s/app/digita-tekton-reporter" $env }}
        property: {{ $property }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
