# =============================================================================
# release-platform.ps1 — cut a release of the platform tree, and put every
# installation the channel admits on it, or the one that is named. Bash twin:
# release-platform.sh (same folder), which does the same in the same order and
# prints the same lines.
# lifecycle/test.sh measures that.
# =============================================================================
#
# USAGE (run from anywhere inside a hostyour-cloud checkout)
#   pwsh ./lifecycle/release-platform.ps1 <x.y.z> <stable|beta|alpha> [fqdn]
#
# THE INPUTS, AND THE THIRD IS OPTIONAL
#   version  — x.y.z, no leading zeros. EVERY RELEASE IS A PATCH BUMP: the first
#              two numbers say what the product is and are the owner's to move.
#   channel  — the maturity CEILING of the release: alpha may reach a dev
#              installation only, beta dev and test, stable any. The channel is
#              part of the release tag; the installation is not.
#   fqdn     — ONE installation to put the release on, and no other. It is the
#              domain of the cluster, the name of its install branch, and the name
#              of its map under clusters/active. One release, one tree, any number
#              of installations: run this again with another fqdn and the tag is
#              REUSED rather than cut a second time.
#
# LEFT OFF, EVERY INSTALLATION ORIGIN CARRIES TAKES THE RELEASE. An installation
# is a branch carrying its own map under clusters/active; each is measured against
# the ceiling by its map's stage line, pinned where the channel admits it, and left
# as it stands — and said so — where it does not. Then the release finishes its own
# repository: every lifecycle/config.*.env beside the tree (the example excepted)
# has PLATFORM_REF rewritten to the tag, in place, and every pinned installation
# whose config stands there is regenerated by regenerate-install-branch beside this
# file — deploy-branch on the machine merges the tag into the branch, which is what
# carries the release; a pin only records it. An installation without a config here
# is pinned and named with the script that carries it. A FIRST machine has no branch
# yet, because the branch is cut by the deploy-branch program the installation itself
# runs, and that program fetches PLATFORM_REF as a TAG, so a commit will not do: the
# tag minted here is what its config names, and once its branch exists the same
# version and channel REUSE this tag, so the machine and every later pin stand on
# one tree. A RELEASE IS THEREFORE A DEPLOY of every installation whose config stands
# beside the tree, and the person cutting it says so when asking for it.
#
# WHAT A PLATFORM RELEASE IS, AND WHAT IT IS NOT. This repository builds nothing
# — no image, no archive, no package. THE TREE AT THE TAG IS THE RELEASE. So
# there is no pipeline to start and nothing to wait for, and this script needs
# nothing but git: no gh, no token, no network service. What it waits on instead
# is the one thing a machine actually needs — that the tag is on the REMOTE,
# because a pin naming a tag the machine cannot fetch is a pin that fails three
# systems away, in a message about a git ref rather than about a release.
#
# WHY THE PIN IS WRITTEN HERE. The line `release: <tag>` in
# clusters/active/<fqdn>.yaml is what says which state an installation stands on,
# and the write belongs where the credential already is: this workstation is
# logged in to this repository, which is both the tree being released and the
# tree carrying the pin. Nothing new has to be created, held or rotated.
#
# NOTHING IS CREATED BEFORE THE TARGET IS KNOWN GOOD. The install branch is
# cloned, its map read and the ceiling checked BEFORE a tag is minted, so a
# mistyped domain or a channel that may not reach that stage costs nothing and
# leaves no tag behind naming a release nobody meant to cut.
#
# WHAT THIS DOES NOT DO. It does not stamp anything, and it touches no file under
# clusters/argocd or clusters/bootstrap. The root-app.yaml beside clusters/argocd
# carries one installation's own domain where this tree carries a placeholder, and
# writing it is the branch programs' act in the catalogue repository — re-run by
# deploy-branch, which regenerate-install-branch.ps1 beside this file performs on
# the machine, and which is the act a person performs after this one. A second
# implementation of that stamping beside them would disagree with them the first
# time either was corrected. The rest of clusters/argocd is a chart the reconciler
# renders from the cluster map, and clusters/bootstrap is seven templates the
# branch programs render onto the install branch, so neither carries a marker this
# act could put anything into.
#
# THE ORDER IS PIN, THEN REGENERATE, and they are two acts on purpose. Between
# them somebody can read what the pin now says and stop. This one ends by naming
# the second, which reads the ref off the pin this one writes rather than being
# told it a second time.
#
# THE TAG GOES ON origin/master AND NEVER ON THE LOCAL BRANCH. What is released
# is what the remote publishes; a local master may carry commits nobody else has,
# and a tag on one of those names a tree no installation could ever fetch. And the
# push gate lets through only the commit that is checked out, so the checkout is
# brought onto origin/master before anything is cut: a master that only lags -
# every unit's release pins master behind it - is fast-forwarded, and one that
# carries commits of its own, or another branch checked out, stops the run before
# a tag exists.
# =============================================================================

[CmdletBinding()]
param(
  [Parameter(Position = 0)][string] $Version = '',
  [Parameter(Position = 1)][string] $Channel = '',
  [Parameter(Position = 2)][string] $Fqdn = ''
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# EVERY git CALL BELOW IS READ BY ITS EXIT CODE, and several of them are probes
# that are MEANT to fail. Newer PowerShell turns a non-zero native exit into a
# terminating error under the preference above, which would end this run on the
# first probe; stated here so the behaviour is the same on every version.
$PSNativeCommandUseErrorActionPreference = $false

# WHAT IS PRINTED IS ASCII, and that is not a typographic preference. The two
# spellings are held to printing the same bytes, and PowerShell writes its output
# in whatever code page the console carries -- so a dash from outside ASCII
# arrives there as a different byte and the pair quietly stops agreeing. The
# comments in these files are read by people and may say what they like.
#
# AND EVERY LINE ENDS IN ONE BYTE. Write-Host and WriteLine end a line with what
# the running system calls a newline, which on Windows is two bytes and on Linux
# one, so the same script would print different bytes on two machines and the
# twin could never be held to matching it. The newline is written out here
# instead, and a carriage return never enters the output at all.
function Stop-Here([string] $Because, [int] $Code = 65) {
  [Console]::Error.Write("release: $Because`n")
  exit $Code
}
function Say([string] $Line) { [Console]::Out.Write("$Line`n") }

# THE VALUE OF ONE TOP-LEVEL KEY, read the way the catalogue's own step writes
# it: a line beginning at column one with the key and a colon. A key of the same
# name indented under `global:` is a different key and is deliberately not seen.
# Surrounding quotes are the notation's and are taken off.
function Read-FileValue([string] $Path, [string] $Key) {
  foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
    if (-not $line.StartsWith("${Key}:")) { continue }
    $value = $line.Substring($Key.Length + 1).Trim()
    if ($value.Length -ge 2) {
      if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
        $value = $value.Substring(1, $value.Length - 2)
      }
    }
    return $value
  }
  return ''
}

# THE LINE IS REPLACED WHERE IT STANDS AND APPENDED ONLY WHERE THE FILE HAS NONE,
# which is the grammar the catalogue's writing step uses. Appending regardless
# would leave two lines for one key, and whatever reads them takes one.
function Write-FileValue([string] $Path, [string] $Key, [string] $Value) {
  $lines = [System.Collections.Generic.List[string]]::new()
  foreach ($line in [System.IO.File]::ReadAllLines($Path)) { $lines.Add($line) }
  $found = $false
  for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i].StartsWith("${Key}:")) {
      $lines[$i] = "${Key}: $Value"
      $found = $true
      break
    }
  }
  if (-not $found) { $lines.Add("${Key}: $Value") }
  [System.IO.File]::WriteAllText($Path, (($lines -join "`n") + "`n"), [System.Text.UTF8Encoding]::new($false))
}

function Read-TextValue([string[]] $Lines, [string] $Key) {
  foreach ($line in $Lines) {
    if (-not $line.StartsWith("${Key}:")) { continue }
    $value = $line.Substring($Key.Length + 1).Trim()
    if ($value.Length -ge 2) {
      if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
        $value = $value.Substring(1, $value.Length - 2)
      }
    }
    return $value
  }
  return ''
}
function Write-ConfigValue([string] $Path, [string] $Key, [string] $Value) {
  $lines = [System.Collections.Generic.List[string]]::new()
  foreach ($line in [System.IO.File]::ReadAllLines($Path)) { $lines.Add($line) }
  $found = $false
  for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i].StartsWith("${Key}=")) {
      $lines[$i] = "${Key}='$Value'"
      $found = $true
      break
    }
  }
  if (-not $found) { $lines.Add("${Key}='$Value'") }
  [System.IO.File]::WriteAllText($Path, (($lines -join "`n") + "`n"), [System.Text.UTF8Encoding]::new($false))
}
function Pin-Installation([string] $Name) {
  $dir = (New-Item -ItemType Directory -Path (Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName()))).FullName
  try {
    git clone --quiet --single-branch --branch $Name $url $dir
    if ($LASTEXITCODE -ne 0) {
      Stop-Here "origin has no branch $Name. An installation is pinned on its own install branch, and there is none of that name" 66
    }
    $mapName = "clusters/active/$Name.yaml"
    $mapFile = Join-Path $dir $mapName
    if (-not (Test-Path -LiteralPath $mapFile)) {
      Stop-Here "branch $Name carries no $mapName. That map is where an installation records what it is, and the pin is one line in it" 66
    }
    $held = Read-FileValue $mapFile 'release'
    if ($held -eq $tag) {
      Say "release: $mapName already records $tag, so it is left as it stands"
    }
    else {
      Write-FileValue $mapFile 'release' $tag
      git -C $dir add -- $mapName
      if ($LASTEXITCODE -ne 0) { Stop-Here "the pin could not be staged in $mapName" }
      git -C $dir commit --quiet -m "release: pin $Name to $tag" -m 'Written by the release of the platform tree, once the tag stood on the remote.'
      if ($LASTEXITCODE -ne 0) { Stop-Here "the pin of $Name to $tag could not be committed" }
      git -C $dir push --quiet origin $Name
      if ($LASTEXITCODE -ne 0) {
        Stop-Here "the pin of $Name to $tag could not be pushed, so it is a pin only this machine believes" 74
      }
      Say "release: pinned $Name to $tag in $mapName"
    }
  }
  finally {
    Remove-Item -Recurse -Force -LiteralPath $dir -ErrorAction SilentlyContinue
  }
}
if (-not $Version -or -not $Channel) {
  Stop-Here 'usage: lifecycle/release-platform.ps1 <x.y.z> <stable|beta|alpha> [fqdn]' 64
}
if ($Version -notmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$') {
  Stop-Here "version must be x.y.z with no leading zeros (got '$Version')" 64
}
$admits = ''
switch ($Channel) {
  'alpha' { $admits = 'dev' }
  'beta' { $admits = 'dev test' }
  'stable' { $admits = 'dev test prod' }
  default { Stop-Here "channel must be stable, beta or alpha (got '$Channel')" 64 }
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  Stop-Here 'git is not on this path, and a platform release is nothing but git'
}
git rev-parse --is-inside-work-tree *> $null
if ($LASTEXITCODE -ne 0) {
  Stop-Here 'not inside a git repository. Run this from a checkout of the platform tree' 66
}

# THE REMOTE VIEW FIRST, for two reasons. Mint-once has to see the tags somebody
# else pushed, or a second workstation mints a second tag for the same version
# and channel instead of reusing the one that exists. And the tag below is put on
# origin/master, which a checkout that has not fetched resolves to whatever it
# last saw.
git fetch --quiet --tags origin *> $null
if ($LASTEXITCODE -ne 0) {
  Stop-Here 'origin could not be fetched, so neither the tag nor the pin would be about what the remote carries' 69
}
git rev-parse --verify --quiet origin/master *> $null
if ($LASTEXITCODE -ne 0) {
  Stop-Here 'origin carries no master, and master is what a platform release is cut from' 69
}
$headSha = (git rev-parse --verify HEAD | Select-Object -First 1)
$originSha = (git rev-parse --verify origin/master | Select-Object -First 1)
if ("$headSha" -ne "$originSha") {
  $branch = (git symbolic-ref --quiet --short HEAD | Select-Object -First 1)
  git merge-base --is-ancestor HEAD origin/master *> $null
  if ("$branch" -ne 'master' -or $LASTEXITCODE -ne 0) {
    Stop-Here 'this checkout is not master, or carries commits origin/master does not, so it cannot be brought onto origin/master: the tag goes there and the push gate lets through only what is checked out. Check out master and push or drop its own commits, then release again'
  }
  git merge --quiet --ff-only origin/master
  if ($LASTEXITCODE -ne 0) {
    Stop-Here 'master lags origin/master and could not be fast-forwarded onto it - the lines above say why. The tag goes on origin/master and the push gate lets through only what is checked out'
  }
  Say 'release: master is fast-forwarded onto origin/master, where the tag goes - the push gate lets through only what is checked out'
}

# EVERYTHING THAT NEEDS AN INSTALLATION STANDS IN THE BLOCK BELOW, and a run that
# names none skips it. What is skipped is the clone, the map, the channel ceiling
# and, at the end of this file, the pin. The mint is not: a tag that names no
# installation is exactly what a first machine is given.
$work = ''
try {
  if ($Fqdn) {
    # THE TREE IS CLONED FRESH FOR THE WRITE. The pin stands on an install branch,
    # and checking one out in the tree somebody is standing in is a thing a release
    # has no business doing.
    $url = (git remote get-url origin | Select-Object -First 1)
    if (-not $url) { Stop-Here 'this checkout has no origin to clone, so there is no branch to pin' 69 }
    $work = (New-Item -ItemType Directory -Path (Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName()))).FullName
    git clone --quiet --single-branch --branch $Fqdn $url $work
    if ($LASTEXITCODE -ne 0) {
      Stop-Here "origin has no branch $Fqdn. An installation is pinned on its own install branch, and there is none of that name" 66
    }

    $map = "clusters/active/$Fqdn.yaml"
    $mapPath = Join-Path $work $map
    if (-not (Test-Path -LiteralPath $mapPath)) {
      Stop-Here "branch $Fqdn carries no $map. That map is where an installation records what it is, and the pin is one line in it" 66
    }

    # THE CEILING IS ENFORCED HERE, and this is the only place that can. The
    # manager's release client only warns because a pipeline refuses afterwards; a
    # platform release has no pipeline, so a refusal that did not happen here would
    # not happen at all, and a prod installation would stand on an alpha tree.
    $stage = Read-FileValue $mapPath 'stage'
    if (-not $stage) {
      Stop-Here "$map on branch $Fqdn states no stage, so the channel ceiling cannot be checked, and a check that cannot measure must not report a pass" 65
    }
    if ($admits.Split(' ') -notcontains $stage) {
      Stop-Here "$Fqdn is stage $stage and channel $Channel admits only: $admits. Nothing else would refuse this, so this does." 65
    }
  }

  # THE STAGE IS NOT A DOMAIN LABEL, and this is the one place that can still say so
  # before a tree reaches a machine. An API group is a reverse domain name fixed by
  # whoever wrote the software - triggers.tekton.dev, cert-manager.io, argoproj.io -
  # and no part of it varies with an installation's stage. Written as the stage
  # placeholder it renders correctly on a dev installation by accident, because the
  # stamp puts "dev" back, and names a group no cluster registers on every other
  # stage. On such a stage the cicd project permits triggers.tekton.<stage>, ArgoCD
  # cannot manage the ClusterInterceptors, and the tekton application stands
  # OutOfSync for ever with the image-builder behind it.
  #
  # READ OFF origin/master, not the working tree: that is the tree this release
  # publishes, and a correction sitting uncommitted beside it would let a release
  # claim a fix nobody can fetch.
  $placed = (& git grep -nE '^[[:space:]]*(-[[:space:]]+)?(group|apiVersion):[[:space:]]*[^[:space:]]*__STAGE__' origin/master -- clusters/argocd 2>$null)
  if ($LASTEXITCODE -gt 1) { $placed = @() }
  $placedLine = (($placed | ForEach-Object { "$_;" }) -join '')
  if ($placedLine) {
    Stop-Here "a stage placeholder stands where an API group or an apiVersion belongs, and neither ever varies with a stage: $placedLine correct it on master and release again" 65
  }
  # MINT-ONCE: exactly one release tag per version and channel. A later run for
  # the same pair reuses it, which is how one release reaches a further
  # installation without a second tree ever being cut.
  $prefix = "$Version-$Channel-"
  $existing = @(git tag -l "$prefix*" | Sort-Object)

  # A TAG THAT NEVER REACHED ORIGIN AND NAMES ANOTHER COMMIT IS RESIDUE, and reusing
  # it aims every retry at the commit a refused push left behind. The tag is minted
  # before it is pushed, so a push the pre-push hook refuses leaves it standing here
  # and nowhere else; the next run finds it, reuses it, and is refused again — for
  # the same reason, printed as if it were about the new attempt, until somebody
  # deletes the tag by hand.
  #
  # A TAG THAT IS ON ORIGIN IS LEFT EXACTLY AS IT STANDS, whatever commit it names.
  # That is mint-once itself: one release per version and channel, reused so a
  # release already cut reaches a second installation without a second tree.
  if ($existing.Count -gt 0) {
    $candidate = $existing[-1]
    git ls-remote --exit-code --tags origin "refs/tags/$candidate" *> $null
    $onOrigin = ($LASTEXITCODE -eq 0)
    $candidateSha = (git rev-parse --verify --quiet "$candidate^{commit}" | Select-Object -First 1)
    $releasedSha = (git rev-parse --verify origin/master | Select-Object -First 1)
    if (-not $onOrigin -and "$candidateSha" -ne "$releasedSha") {
      $candidateShort = (git rev-parse --short=7 "$candidate^{commit}" | Select-Object -First 1)
      Say "release: $candidate stands on this workstation only and names $candidateShort, not the commit this release is cut from. A run whose push was refused left it behind; it is dropped and cut again."
      git tag -d $candidate *> $null
      if ($LASTEXITCODE -ne 0) {
        Stop-Here "the leftover tag $candidate could not be dropped, and reusing it would put this release on a commit nobody is releasing" 69
      }
      $existing = @()
    }
  }

  if ($existing.Count -gt 0) {
    $tag = $existing[-1]
    if ($Fqdn) {
      Say "release: reusing $tag. One release per version and channel, so putting it on $Fqdn cuts nothing new"
    }
    else {
      Say "release: reusing $tag. One release per version and channel, so this run cuts nothing new"
    }
  }
  else {
    $ts14 = [DateTime]::UtcNow.ToString('yyyyMMddHHmmss')
    $tag = "$Version-$Channel-$ts14"
    git tag -a $tag -m 'the platform, cut as a release' origin/master
    if ($LASTEXITCODE -ne 0) { Stop-Here "the tag $tag could not be put on origin/master" }
    $sha7 = (git rev-parse --short=7 "$tag^{commit}" | Select-Object -First 1)
    Say "release: minted $tag on origin/master (commit $sha7)"
    Say 'release: this tree builds nothing. The tree at the tag IS the release, so there is no image and nothing further to wait for'
  }

  git rev-parse --verify --quiet master *> $null
  if ($LASTEXITCODE -eq 0) {
    $ahead = (git rev-list --count origin/master..master | Select-Object -First 1)
    if ("$ahead" -ne '0') {
      Say "release: your local master is $ahead commits ahead of origin/master, and those commits are not in this release"
    }
  }

  # NOTHING IS PINNED BEFORE IT EXISTS. The push is what makes the tag fetchable;
  # the read-back is what proves it, and it is asked of the REMOTE rather than of
  # this checkout, which already has the tag whatever the remote thinks.
  git push --quiet origin "refs/tags/$tag"
  if ($LASTEXITCODE -ne 0) {
    Stop-Here "the tag $tag could not be pushed to origin, so it exists on this machine only and nothing was pinned" 74
  }
  $onRemote = @(git ls-remote --tags origin "refs/tags/$tag")
  if ($onRemote.Count -eq 0) {
    Stop-Here "origin does not carry $tag after the push, so a machine could not fetch it and nothing was pinned" 74
  }
  Say 'release: the tag stands on the remote, so a machine that fetches origin can resolve it'

  # EVERY INSTALLATION ORIGIN CARRIES TAKES THE RELEASE, or the one that was named. An
  # installation is a branch carrying its own map, clusters/active/<branch>.yaml; the
  # ceiling is measured against each map's stage, and an installation the channel does
  # not admit is left as it stands and said so. A first machine, whose branch does not
  # exist yet, takes the tag as PLATFORM_REF and cuts its branch from it.
  $pinned = [System.Collections.Generic.List[string]]::new()
  if ($Fqdn) {
    if ($work) { Remove-Item -Recurse -Force -LiteralPath $work -ErrorAction SilentlyContinue; $work = '' }
    Pin-Installation $Fqdn
    $pinned.Add($Fqdn)
  }
  else {
    $url = (git remote get-url origin | Select-Object -First 1)
    if (-not $url) { Stop-Here 'this checkout has no origin to clone, so there is no branch to pin' 69 }
    $found = $false
    $heads = @(git ls-remote --heads origin | ForEach-Object { ($_ -split "`t")[1] -replace '^refs/heads/', '' } | Sort-Object)
    foreach ($branch in $heads) {
      if ($branch -eq 'master') { continue }
      git cat-file -e "refs/remotes/origin/${branch}:clusters/active/${branch}.yaml" *> $null
      if ($LASTEXITCODE -ne 0) { continue }
      $found = $true
      $stage = Read-TextValue (git show "refs/remotes/origin/${branch}:clusters/active/${branch}.yaml") 'stage'
      if ($admits.Split(' ') -contains $stage) {
        Pin-Installation $branch
        $pinned.Add($branch)
      }
      else {
        $shown = if ($stage) { $stage } else { 'unstated' }
        Say "release: $branch is stage $shown and channel $Channel admits only: $admits - left as it stands"
      }
    }
    if (-not $found) {
      Say "release: origin carries no installation yet, so nothing is pinned. A first machine names $tag as PLATFORM_REF in its config and cuts its branch from it"
    }
  }
}
finally {
  if ($work) { Remove-Item -Recurse -Force -LiteralPath $work -ErrorAction SilentlyContinue }
}
# THE CONFIGS OF THIS CHECKOUT NAME THE RELEASE A FIRST MACHINE IS CUT FROM. Every
# lifecycle/config.*.env beside the tree this runs in, the example excepted, has its
# PLATFORM_REF rewritten in place — the file keeps its identity and with it the
# owner-only rights the launcher demands.
$configDir = Join-Path (git rev-parse --show-toplevel | Select-Object -First 1) 'lifecycle'
$written = 0
foreach ($config in @(Get-ChildItem -LiteralPath $configDir -Filter 'config.*.env' -File -ErrorAction SilentlyContinue | Sort-Object Name)) {
  if ($config.Name -eq 'config.example.env') { continue }
  Write-ConfigValue $config.FullName 'PLATFORM_REF' $tag
  $written += 1
}
if ($written -eq 0) {
  Say 'release: no config beside this tree names a PLATFORM_REF, so none was written'
}
else {
  Say "release: PLATFORM_REF=$tag written into $written config(s) under lifecycle/"
}
# THE PIN RECORDS THE STATE; THE REGENERATION CARRIES IT. Every source of every
# Application reads the install branch, so an installation stands on the release
# only once deploy-branch has merged the tag into its branch — which
# regenerate-install-branch beside this file performs on the machine, with the
# installation's config. Where that config stands beside this tree, the release
# performs it; where it does not, the release says which script does and stops
# short of it.
foreach ($fqdnPinned in $pinned) {
  $label = $fqdnPinned.Split('.')[0]
  $config = Join-Path $configDir "config.$label.env"
  if (Test-Path -LiteralPath $config) {
    Say "release: regenerating $fqdnPinned with config.$label.env - the release is a deploy of this installation"
    & pwsh -NoProfile -NoLogo -File (Join-Path $PSScriptRoot 'regenerate-install-branch.ps1') $fqdnPinned $config
    if ($LASTEXITCODE -ne 0) {
      Stop-Here "$fqdnPinned could not be regenerated onto $tag; its pin stands, its branch does not carry the release yet, and every installation after it in the list was not touched" 70
    }
  }
  else {
    Say "release: no config for $fqdnPinned beside this tree (lifecycle/config.$label.env), so it is pinned and not regenerated. Bring it onto $tag with:"
    Say "release:     bash lifecycle/regenerate-install-branch.sh $fqdnPinned <config>"
    Say "release:     pwsh ./lifecycle/regenerate-install-branch.ps1 $fqdnPinned <config>"
  }
}
