name: "digita-docs"
repoURL: "https://github.com/digitaplatform/digita-docs.git"
owner: "digitaplatform"
onboardedAt: "2026-10-09T13:25:34.360Z"
suspended: false
quiesced: false
removing: false
builds: []
