name: "digita-catalog-simetrix"
repoURL: "https://github.com/digitaplatform/digita-catalog-simetrix.git"
owner: "simetrix"
onboardedAt: "2026-09-26T23:52:20.378Z"
suspended: false
quiesced: false
removing: false
builds: ["digita-catalog-simetrix"]
